# v0.1.0
version: "3"
services:
  3laws_rdm:
    container_name: 3laws_rdm
    image: @DOCKER_IMAGE_LINK@
    volumes:
      - /etc/machine-id:/3laws_robotics/machine-id
      - /dev/shm:/dev/shm
    stop_signal: SIGINT
    pid: host
    network_mode: host
    user: @USERID@:@GROUPID@
    environment:
      - "LAWS3_ROBOT_ID=@LAWS3_ROBOT_ID@"

  watchtower:
    container_name: 3laws_rdm_updater
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - @HOME@/.docker/3laws/config.json:/config.json
    command: 3laws_rdm --log-level warn --cleanup --schedule "0 * * * * *"
    labels:
      com.centurylinklabs.watchtower.stop-signal: SIGINT
